### ISSUE TITLE
Package r-gpur and help with setup with OpenCL with AMDGPU

### ISSUE THREAD

**Issue by wdkrnls** [guix-science/guix-science-nonfree#1]
One thing that I was really hoping to use my guix system for was fast matrix computation with GPUs to accelerate my statistical computations. Would you be able to provide some way of using MESA or AMDGPU-pro openCl runtime with the mostly free AMDGPU graphics driver to make clinfo recognize the GPU and let R users work with matrices inside of graphics cards in R through the gpur package?

**Comment by PromyLOPh** [comment]
Why AMDGPU-pro? There’s a complete free/open-source ROCm OpenCL runtime for AMD GPU’s. It’s not in Guix proper yet though (and probably never will be, because ”non-free firmware”). Packaging it is a bit tricky though, because it’s quite big. I don’t have much time, but I can probably help if any issues arise.

**Comment by wdkrnls** [comment]
I would love to have rocm if possible... just looked like more of a headache. Honestly, I was hoping the MESA stuff would be the lowest hanging fruit. I'm just not skilled packaging this kind of stuff. I did spend a bit of time last year or so digging into it. I posted a ton of links on an [issue thread for nonguix](https://gitlab.com/nonguix/nonguix/-/issues/37). You can still find that there. However, since opencl is kind of a niche science thing here, I thought it makes more sense bring it up in this forum.

**Comment by PromyLOPh** [comment]
With a little help from the Gentoo folks ROCm does not seem that bad right now. I packaged it until rocm-opencl-runtime, which cannot find libOpenCL.so for some reason right now.

**Comment by PromyLOPh** [comment]
The patchset is pending review: https://issues.guix.gnu.org/49907

**Comment by PromyLOPh** [comment]
And it has been merged into Guix proper now.

**Comment by wdkrnls** [comment]
Thank you so much!
