### ISSUE TITLE
Datasaurus is free software

### ISSUE THREAD

**Issue by rekado** [guix-science/guix-science-nonfree#2]
In the R DESCRIPTION files "MIT + license file" are generally used to clarify the authorship.  The license file merely contains the copyright, while the license that applies is the Expat/MIT license.

This is a common idiom.  It does not mean that the package is covered under the Expat/MIT license *and* "all right reserved" by the copyright holder.

The package could be moved to Guix proper.

**Comment by PromyLOPh** [comment]
Done. This idiom is very confusing though.
